services:
  backend:
    image: ghcr.io/waraqaweb/waraqa-backend:${DEPLOY_IMAGE_TAG:-main}
    build: null

  frontend:
    image: ghcr.io/waraqaweb/waraqa-frontend:${DEPLOY_IMAGE_TAG:-main}
    build: null

  nginx:
    image: ghcr.io/waraqaweb/waraqa-nginx:${DEPLOY_IMAGE_TAG:-main}
    build: null
