// Centralized topics/subjects config used across the dashboard.

// Quran Surahs List
const surahs = [
  "(Al-Fatiha) الفاتحة", "(Al-Baqarah) البقرة", "(Aal-E-Imran) آل عمران", "(An-Nisa) النساء",
  "(Al-Maidah) المائدة", "(Al-An'am) الأنعام", "(Al-A'raf) الأعراف", "(Al-Anfal) الأنفال",
  "(At-Tawbah) التوبة", "(Yunus) يونس", "(Hud) هود", "(Yusuf) يوسف", "(Ar-Ra'd) الرعد",
  "(Ibrahim) إبراهيم", "(Al-Hijr) الحجر", "(An-Nahl) النحل", "(Al-Isra) الإسراء",
  "(Al-Kahf) الكهف", "(Maryam) مريم", "(Ta-Ha) طه", "(Al-Anbiya) الأنبياء", "(Al-Hajj) الحج",
  "(Al-Muminun) المؤمنون", "(An-Nur) النور", "(Al-Furqan) الفرقان", "(Ash-Shu'ara) الشعراء",
  "(An-Naml) النمل", "(Al-Qasas) القصص", "(Al-Ankabut) العنكبوت", "(Ar-Rum) الروم",
  "(Luqman) لقمان", "(As-Sajda) السجدة", "(Al-Ahzab) الأحزاب", "(Saba) سبأ", "(Fatir) فاطر",
  "(Ya-Sin) يس", "(As-Saffat) الصافات", "(Sad) ص", "(Az-Zumar) الزمر", "(Ghafir) غافر",
  "(Fussilat) فصلت", "(Ash-Shura) الشورى", "(Az-Zukhruf) الزخرف", "(Ad-Dukhan) الدخان",
  "(Al-Jathiya) الجاثية", "(Al-Ahqaf) الأحقاف", "(Muhammad) محمد", "(Al-Fath) الفتح",
  "(Al-Hujurat) الحجرات", "(Qaf) ق", "(Adh-Dhariyat) الذاريات", "(At-Tur) الطور",
  "(An-Najm) النجم", "(Al-Qamar) القمر", "(Ar-Rahman) الرحمن", "(Al-Waqia) الواقعة",
  "(Al-Hadid) الحديد", "(Al-Mujadila) المجادلة", "(Al-Hashr) الحشر", "(Al-Mumtahina) الممتحنة",
  "(As-Saff) الصف", "(Al-Jumu'a) الجمعة", "(Al-Munafiqun) المنافقون", "(At-Taghabun) التغابن",
  "(At-Talaq) الطلاق", "(At-Tahrim) التحريم", "(Al-Mulk) الملك", "(Al-Qalam) القلم",
  "(Al-Haaqqa) الحاقة", "(Al-Ma'arij) المعارج", "(Nuh) نوح", "(Al-Jinn) الجن",
  "(Al-Muzzammil) المزمل", "(Al-Muddathir) المدثر", "(Al-Qiyama) القيامة", "(Al-Insan) الإنسان",
  "(Al-Mursalat) المرسلات", "(An-Naba) النبأ", "(An-Nazi'at) النازعات", "(Abasa) عبس",
  "(At-Takwir) التكوير", "(Al-Infitar) الإنفطار", "(Al-Mutaffifin) المطففين",
  "(Al-Inshiqaq) الإنشقاق", "(Al-Buruj) البروج", "(At-Tariq) الطارق", "(Al-A'la) الأعلى",
  "(Al-Ghashiya) الغاشية", "(Al-Fajr) الفجر", "(Al-Balad) البلد", "(Ash-Shams) الشمس",
  "(Al-Lail) الليل", "(Ad-Duha) الضحى", "(Ash-Sharh) الشرح", "(At-Tin) التين",
  "(Al-Alaq) العلق", "(Al-Qadr) القدر", "(Al-Bayyina) البينة", "(Az-Zalzala) الزلزلة",
  "(Al-Adiyat) العاديات", "(Al-Qaria) القارعة", "(At-Takathur) التكاثر", "(Al-Asr) العصر",
  "(Al-Humaza) الهمزة", "(Al-Fil) الفيل", "(Quraish) قريش", "(Al-Ma'un) الماعون",
  "(Al-Kawthar) الكوثر", "(Al-Kafiroon) الكافرون", "(An-Nasr) النصر", "(Al-Masad) المسد",
  "(Al-Ikhlas) الإخلاص", "(Al-Falaq) الفلق", "(An-Nas) الناس"
];

// Subjects + Topics Mapping
const topicsMap = {
  Foundation: [
    "Arabic alphabet",
    "Arabic alphabet (Fathah)",
    "Arabic alphabet (Kasrah)",
    "Arabic alphabet (Dammah)",
    "Medd letters (ا - و - ي)",
    "Arabic alphabet (Tanween)",
    "Arabic alphabet (Sukoon)",
    "Lam Qamaryyah (Voiced)",
    "Stoppage with Sukoon on the word",
    "Shaddah with different Diacritics",
    "Shaddah + Diacritics + Medd",
    "Similar letters pronunciation and writing",
    "Lam Shamsyyah (Silent)",
    "Stoppage on Tanween and circled Taa",
    "Shaddah with Tanween",
    "Stoppage on Qalqalah or Ghunnah",
    "Double Sakin letters",
    "Divide the word into syllables",
  ],
  "Tajweed Basics": [
    "An introduction to Tajweed rules",
    "Rules of Noon and Meem Mushaddad",
    "Qalqalah",
    "The heavy and light letters",
    "Laam in the exalted name of Allah",
    "Ruling of RAA letter being heavy or light",
    "Noon Sakinah and Tanween intro",
    "Izhar Halqi",
    "Iqlaab",
    "Idghaam",
    "Ikhfaa Haqiqi",
    "Rules of Meem Saakinah",
    "Ikhfaa Shafawi",
    "Idghaam Mutamathelayn Sagheer",
    "Izhaar Shafawi",
  ],
  "Tajweed Inter.": [
    "Meddd Tabee",
    "Meddd Leen",
    "Medd Badal",
    "Medd Wajib Mutassil",
    "Medd Jaez Munfasil",
    "Meddd Aridh Lissukoon",
    "Medd Laazim Kalemee",
    "Medd Laazim Harfee",
    "Medd Silah",
    "Medd Ewad",
    "Medd Tamkeen",
  ],
  "Qari Prog.": [
    "An introduction to Qiraat",
    "Articulation points",
    "Al-Jawf – Interior/Chest Area",
    "Al-Halq – The Throat",
    "Al-Lisaan – The Tongue",
    "Al-Shafataan – Lips",
    "Al-Khaysoom – Nasal Passage",
    "Sifat al-Huruf",
    "Permanent Qualities with opposites",
    "Al-Jahr and Al-Hams",
    "Asheddah, Attawusut and Arrakhawa",
    "Istifaal and Isteelaa",
    "Al-infetaah and Al-Itbaaq",
    "Al-Izlaaq and Al-Ismaat",
    "Permanent Qualities without opposites",
    "Alqaqala",
    "As-Safeer",
    "Al-Leen",
    "Al-Inhiraf",
    "At-Takreer",
    "At-Tafasshy",
    "Istitaalah",
    "Noon Sakinah and Tanween",
    "Rules of Meem Saakin",
    "Medd and Qasr",
    "Al-Waqf and Ibtidaa'",
    "Isti'adhah and Basmallah",
    "Hamzat al-Wasl and Laam types",
  ],
  "Khatmah Prog.": [],

  "Short Surahs": [
    "(Al-A'la) الأعلى",
    "(Al-Ghashiya) الغاشية", "(Al-Fajr) الفجر", "(Al-Balad) البلد", "(Ash-Shams) الشمس",
    "(Al-Lail) الليل", "(Ad-Duha) الضحى", "(Ash-Sharh) الشرح", "(At-Tin) التين",
    "(Al-Alaq) العلق", "(Al-Qadr) القدر", "(Al-Bayyina) البينة", "(Az-Zalzala) الزلزلة",
    "(Al-Adiyat) العاديات", "(Al-Qaria) القارعة", "(At-Takathur) التكاثر", "(Al-Asr) العصر",
    "(Al-Humaza) الهمزة", "(Al-Fil) الفيل", "(Quraish) قريش", "(Al-Ma'un) الماعون",
    "(Al-Kawthar) الكوثر", "(Al-Kafiroon) الكافرون", "(An-Nasr) النصر", "(Al-Masad) المسد",
    "(Al-Ikhlas) الإخلاص", "(Al-Falaq) الفلق", "(An-Nas) الناس"
  ],
  "Hafez Prog.": [],
  "Ijazah Prog.": [],
};

// Dynamic subjects list
const subjects = [
  ...Object.keys(topicsMap),
  "Basic Arabic",
  "Inter. Arabic",
  "Upper-Inter. Arabic",
  "Advanced Arabic",
  "Classical Arabic",
  "Religion Facts",
  "Classical Intro",
  "Classical Books",
];

export default topicsMap;
export { subjects, surahs };
